// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateLightCommand.proto

package proto.messages;

public final class UpdateLightCommandOuterClass {
  private UpdateLightCommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpdateLightCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.messages.UpdateLightCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 msg_version = 1;</code>
     */
    int getMsgVersion();

    /**
     * <code>optional string light_id = 2;</code>
     */
    java.lang.String getLightId();
    /**
     * <code>optional string light_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getLightIdBytes();

    /**
     * <code>optional int32 rgb_red = 3;</code>
     */
    int getRgbRed();

    /**
     * <code>optional int32 rgb_green = 4;</code>
     */
    int getRgbGreen();

    /**
     * <code>optional int32 rgb_blue = 5;</code>
     */
    int getRgbBlue();

    /**
     * <code>optional bool is_on = 6;</code>
     */
    boolean getIsOn();
  }
  /**
   * Protobuf type {@code proto.messages.UpdateLightCommand}
   */
  public  static final class UpdateLightCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.messages.UpdateLightCommand)
      UpdateLightCommandOrBuilder {
    // Use UpdateLightCommand.newBuilder() to construct.
    private UpdateLightCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UpdateLightCommand() {
      msgVersion_ = 0;
      lightId_ = "";
      rgbRed_ = 0;
      rgbGreen_ = 0;
      rgbBlue_ = 0;
      isOn_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateLightCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              msgVersion_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              lightId_ = s;
              break;
            }
            case 24: {

              rgbRed_ = input.readInt32();
              break;
            }
            case 32: {

              rgbGreen_ = input.readInt32();
              break;
            }
            case 40: {

              rgbBlue_ = input.readInt32();
              break;
            }
            case 48: {

              isOn_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.messages.UpdateLightCommandOuterClass.internal_static_proto_messages_UpdateLightCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.messages.UpdateLightCommandOuterClass.internal_static_proto_messages_UpdateLightCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand.class, proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand.Builder.class);
    }

    public static final int MSG_VERSION_FIELD_NUMBER = 1;
    private int msgVersion_;
    /**
     * <code>optional int32 msg_version = 1;</code>
     */
    public int getMsgVersion() {
      return msgVersion_;
    }

    public static final int LIGHT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object lightId_;
    /**
     * <code>optional string light_id = 2;</code>
     */
    public java.lang.String getLightId() {
      java.lang.Object ref = lightId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lightId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string light_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLightIdBytes() {
      java.lang.Object ref = lightId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lightId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RGB_RED_FIELD_NUMBER = 3;
    private int rgbRed_;
    /**
     * <code>optional int32 rgb_red = 3;</code>
     */
    public int getRgbRed() {
      return rgbRed_;
    }

    public static final int RGB_GREEN_FIELD_NUMBER = 4;
    private int rgbGreen_;
    /**
     * <code>optional int32 rgb_green = 4;</code>
     */
    public int getRgbGreen() {
      return rgbGreen_;
    }

    public static final int RGB_BLUE_FIELD_NUMBER = 5;
    private int rgbBlue_;
    /**
     * <code>optional int32 rgb_blue = 5;</code>
     */
    public int getRgbBlue() {
      return rgbBlue_;
    }

    public static final int IS_ON_FIELD_NUMBER = 6;
    private boolean isOn_;
    /**
     * <code>optional bool is_on = 6;</code>
     */
    public boolean getIsOn() {
      return isOn_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgVersion_ != 0) {
        output.writeInt32(1, msgVersion_);
      }
      if (!getLightIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, lightId_);
      }
      if (rgbRed_ != 0) {
        output.writeInt32(3, rgbRed_);
      }
      if (rgbGreen_ != 0) {
        output.writeInt32(4, rgbGreen_);
      }
      if (rgbBlue_ != 0) {
        output.writeInt32(5, rgbBlue_);
      }
      if (isOn_ != false) {
        output.writeBool(6, isOn_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgVersion_);
      }
      if (!getLightIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, lightId_);
      }
      if (rgbRed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rgbRed_);
      }
      if (rgbGreen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rgbGreen_);
      }
      if (rgbBlue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, rgbBlue_);
      }
      if (isOn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isOn_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.messages.UpdateLightCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.messages.UpdateLightCommand)
        proto.messages.UpdateLightCommandOuterClass.UpdateLightCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  proto.messages.UpdateLightCommandOuterClass.internal_static_proto_messages_UpdateLightCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  proto.messages.UpdateLightCommandOuterClass.internal_static_proto_messages_UpdateLightCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand.class, proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand.Builder.class);
      }

      // Construct using proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgVersion_ = 0;

        lightId_ = "";

        rgbRed_ = 0;

        rgbGreen_ = 0;

        rgbBlue_ = 0;

        isOn_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  proto.messages.UpdateLightCommandOuterClass.internal_static_proto_messages_UpdateLightCommand_descriptor;
      }

      public proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand getDefaultInstanceForType() {
        return  proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand.getDefaultInstance();
      }

      public proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand build() {
                proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand buildPartial() {
                proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand result = new proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand(this);
        result.msgVersion_ = msgVersion_;
        result.lightId_ = lightId_;
        result.rgbRed_ = rgbRed_;
        result.rgbGreen_ = rgbGreen_;
        result.rgbBlue_ = rgbBlue_;
        result.isOn_ = isOn_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand) {
          return mergeFrom((proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand other) {
        if (other == proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand.getDefaultInstance()) return this;
        if (other.getMsgVersion() != 0) {
          setMsgVersion(other.getMsgVersion());
        }
        if (!other.getLightId().isEmpty()) {
          lightId_ = other.lightId_;
          onChanged();
        }
        if (other.getRgbRed() != 0) {
          setRgbRed(other.getRgbRed());
        }
        if (other.getRgbGreen() != 0) {
          setRgbGreen(other.getRgbGreen());
        }
        if (other.getRgbBlue() != 0) {
          setRgbBlue(other.getRgbBlue());
        }
        if (other.getIsOn() != false) {
          setIsOn(other.getIsOn());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgVersion_ ;
      /**
       * <code>optional int32 msg_version = 1;</code>
       */
      public int getMsgVersion() {
        return msgVersion_;
      }
      /**
       * <code>optional int32 msg_version = 1;</code>
       */
      public Builder setMsgVersion(int value) {
        
        msgVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msg_version = 1;</code>
       */
      public Builder clearMsgVersion() {
        
        msgVersion_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object lightId_ = "";
      /**
       * <code>optional string light_id = 2;</code>
       */
      public java.lang.String getLightId() {
        java.lang.Object ref = lightId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lightId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string light_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLightIdBytes() {
        java.lang.Object ref = lightId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lightId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string light_id = 2;</code>
       */
      public Builder setLightId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lightId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string light_id = 2;</code>
       */
      public Builder clearLightId() {
        
        lightId_ = getDefaultInstance().getLightId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string light_id = 2;</code>
       */
      public Builder setLightIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lightId_ = value;
        onChanged();
        return this;
      }

      private int rgbRed_ ;
      /**
       * <code>optional int32 rgb_red = 3;</code>
       */
      public int getRgbRed() {
        return rgbRed_;
      }
      /**
       * <code>optional int32 rgb_red = 3;</code>
       */
      public Builder setRgbRed(int value) {
        
        rgbRed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rgb_red = 3;</code>
       */
      public Builder clearRgbRed() {
        
        rgbRed_ = 0;
        onChanged();
        return this;
      }

      private int rgbGreen_ ;
      /**
       * <code>optional int32 rgb_green = 4;</code>
       */
      public int getRgbGreen() {
        return rgbGreen_;
      }
      /**
       * <code>optional int32 rgb_green = 4;</code>
       */
      public Builder setRgbGreen(int value) {
        
        rgbGreen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rgb_green = 4;</code>
       */
      public Builder clearRgbGreen() {
        
        rgbGreen_ = 0;
        onChanged();
        return this;
      }

      private int rgbBlue_ ;
      /**
       * <code>optional int32 rgb_blue = 5;</code>
       */
      public int getRgbBlue() {
        return rgbBlue_;
      }
      /**
       * <code>optional int32 rgb_blue = 5;</code>
       */
      public Builder setRgbBlue(int value) {
        
        rgbBlue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rgb_blue = 5;</code>
       */
      public Builder clearRgbBlue() {
        
        rgbBlue_ = 0;
        onChanged();
        return this;
      }

      private boolean isOn_ ;
      /**
       * <code>optional bool is_on = 6;</code>
       */
      public boolean getIsOn() {
        return isOn_;
      }
      /**
       * <code>optional bool is_on = 6;</code>
       */
      public Builder setIsOn(boolean value) {
        
        isOn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_on = 6;</code>
       */
      public Builder clearIsOn() {
        
        isOn_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.messages.UpdateLightCommand)
    }

    // @@protoc_insertion_point(class_scope:proto.messages.UpdateLightCommand)
    private static final proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand();
    }

    public static proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateLightCommand>
        PARSER = new com.google.protobuf.AbstractParser<UpdateLightCommand>() {
      public UpdateLightCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UpdateLightCommand(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<UpdateLightCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateLightCommand> getParserForType() {
      return PARSER;
    }

    public proto.messages.UpdateLightCommandOuterClass.UpdateLightCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_messages_UpdateLightCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_messages_UpdateLightCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030UpdateLightCommand.proto\022\016proto.messag" +
      "es\"\200\001\n\022UpdateLightCommand\022\023\n\013msg_version" +
      "\030\001 \001(\005\022\020\n\010light_id\030\002 \001(\t\022\017\n\007rgb_red\030\003 \001(" +
      "\005\022\021\n\trgb_green\030\004 \001(\005\022\020\n\010rgb_blue\030\005 \001(\005\022\r" +
      "\n\005is_on\030\006 \001(\010b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_messages_UpdateLightCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_messages_UpdateLightCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_messages_UpdateLightCommand_descriptor,
        new java.lang.String[] { "MsgVersion", "LightId", "RgbRed", "RgbGreen", "RgbBlue", "IsOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
